//! Every user action is a `Command`. Menus, keybindings and the command palette all dispatch
//! through here, so one table defines titles, ids and default Mac shortcuts.

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Command {
    /// A command an extension contributes (an index into `ext_commands`).
    Ext(u16),
    NewFile,
    OpenFolder,
    OpenRecent,
    InsertSnippet,
    ClearRecent,
    CloseFolder,
    Quit,
    Save,
    CloseEditor,
    ToggleSidebar,
    TogglePanel,
    ToggleAuxiliaryBar,
    AssistantNewChat,
    AssistantFocus,
    OutlineFocus,
    TimelineFocus,
    ToggleMinimap,
    ToggleWordWrap,
    SplitEditor,
    ShowExplorer,
    ShowSearch,
    ShowScm,
    ShowDebug,
    ShowExtensions,
    ExtensionsInstallVsix,
    ExtensionsInstallFromLocation,
    ExtensionsOpenFolder,
    ExtensionsCheckForUpdates,
    ExtensionsUpdateAll,
    RestartExtensionHost,
    CheckForUpdates,
    RestartToUpdate,
    RestartLanguageServer,
    StopLanguageServers,
    FocusGroup1,
    FocusGroup2,
    FocusGroup3,
    QuickOpen,
    CommandPalette,
    Undo,
    Redo,
    Cut,
    Copy,
    Paste,
    SelectAll,
    ToggleComment,
    RefreshExplorer,
    GoToDefinition,
    Rename,
    StartLinkedEditing,
    GoToReferences,
    GotoSymbol,
    TriggerParameterHints,
    ShowAllSymbols,
    GotoLine,
    QuickFix,
    FormatDocument,
    FormatSelection,
    TriggerSuggest,
    ToggleTerminal,
    NewTerminal,
    KillTerminal,
    SplitTerminal,
    FocusNextTerminal,
    FocusPreviousTerminal,
    FocusNextTerminalPane,
    FocusPreviousTerminalPane,
    ReplaceInFiles,
    Find,
    FindReplace,
    FindNext,
    FindPrevious,
    GitCommit,
    GitStageAll,
    GitStageSelectedRanges,
    GitUnstageSelectedRanges,
    GitRevertSelectedRanges,
    GitRefresh,
    GitInit,
    GitOpenChanges,
    NextChange,
    PreviousChange,
    OpenSettings,
    OpenKeybindings,
    OpenKeybindingsFile,
    KeepEditor,
    OpenSettingsJson,
    OpenWorkspaceSettingsJson,
    SelectTheme,
    InsertCursorAbove,
    InsertCursorBelow,
    InsertCursorAtLineEnds,
    AddNextOccurrence,
    AddPreviousOccurrence,
    MoveToNextOccurrence,
    SelectAllOccurrences,
    JumpToBracket,
    SelectToBracket,
    Fold,
    Unfold,
    ToggleFold,
    FoldRecursively,
    UnfoldRecursively,
    FoldAll,
    UnfoldAll,
    GitCheckout,
    GitCheckoutDetached,
    GitCreateBranch,
    GitCreateBranchFrom,
    GitRenameBranch,
    GitDeleteBranch,
    GitMerge,
    GitAbortMerge,
    GitRebase,
    GitAbortRebase,
    GitContinueRebase,
    GitFetch,
    GitFetchPrune,
    GitFetchAll,
    GitPull,
    GitPullRebase,
    GitPush,
    GitPushForce,
    GitSync,
    GitPublish,
    GitCommitAmend,
    GitCommitPush,
    GitCommitSync,
    GitUndoCommit,
    GitUnstageAll,
    GitDiscardAll,
    GitStash,
    GitStashUntracked,
    GitStashStaged,
    GitStashPopLatest,
    GitStashPop,
    GitStashApplyLatest,
    GitStashApply,
    GitStashDrop,
    GitStashDropAll,
    GitAddRemote,
    GitRemoveRemote,
    GitCreateTag,
    GitDeleteTag,
    GitClone,
    ConflictAcceptAllCurrent,
    ConflictAcceptAllIncoming,
    ConflictAcceptAllBoth,
    ConflictNext,
    ConflictPrevious,
    DebugStart,
    DebugRun,
    DebugStop,
    DebugRestart,
    DebugContinue,
    DebugPause,
    DebugStepOver,
    DebugStepInto,
    DebugStepOut,
    ToggleBreakpoint,
    ConditionalBreakpoint,
    AddLogpoint,
    EnableAllBreakpoints,
    DisableAllBreakpoints,
    RemoveAllBreakpoints,
    ToggleBreakpointsActivated,
    DebugConfigure,
    DebugSelectAndStart,
    DebugAddWatch,
    ToggleDebugConsole,
    RunTask,
    RunBuildTask,
    TerminateTask,
    ConfigureTasks,
    ExplorerNewFile,
    ExplorerNewFolder,
    ExplorerRename,
    ExplorerDelete,
    CopyFilePath,
    CopyRelativeFilePath,
    RevealInFinder,
    OpenInTerminal,
    CollapseExplorerFolders,
    SaveAs,
    SaveAll,
    RevertFile,
    CloseOtherEditors,
    CloseEditorsToTheRight,
    CloseSavedEditors,
    CloseGroupEditors,
    CloseAllEditors,
    RevealInExplorer,
    SelectForCompare,
    CompareWithSelected,
    CompareWithSaved,
    CompareFileWith,
    PeekDefinition,
    MarkdownPreview,
    MarkdownPreviewSide,
    ToggleZenMode,
    ShowCallHierarchy,
    ShowTypeHierarchy,
    EmmetExpandAbbreviation,
    EmmetWrapWithAbbreviation,
    ChangeLanguageMode,
    ShowTesting,
    TestingRunAll,
    TestingRunAtCursor,
    TestingDebugAtCursor,
    TestingRunCurrentFile,
    TestingReRunLastRun,
    TestingReRunFailed,
    TestingCancel,
    TestingRefresh,
    TestingShowOutput,
    TestingClearResults,
    TestingCollapseAll,
    NewSearchEditor,
    NewSearchEditorToSide,
    OpenSearchInEditor,
    SearchEditorRerun,
    SearchEditorToggleContext,
    SearchEditorIncreaseContext,
    SearchEditorDecreaseContext,
    SearchEditorFocusInput,
    SearchEditorDeleteFileResults,
    SearchEditorSelectAllMatches,
    GitOpenMergeEditor,
    MergeNextConflict,
    MergePreviousConflict,
    MergeAcceptAllInput1,
    MergeAcceptAllInput2,
    MergeAcceptAllCombination,
    MergeResetResult,
    MergeComplete,
    OpenWorkspaceFromFile,
    AddFolderToWorkspace,
    RemoveFolderFromWorkspace,
    SaveWorkspaceAs,
}

/// A keyboard shortcut. `key` is a lowercase character or a named key like "\\".
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Shortcut {
    pub cmd: bool,
    pub shift: bool,
    pub alt: bool,
    pub ctrl: bool,
    pub key: &'static str,
}

const fn cmd(key: &'static str) -> Shortcut {
    Shortcut { cmd: true, shift: false, alt: false, ctrl: false, key }
}

const fn cmd_shift(key: &'static str) -> Shortcut {
    Shortcut { cmd: true, shift: true, alt: false, ctrl: false, key }
}

const fn plain(key: &'static str) -> Shortcut {
    Shortcut { cmd: false, shift: false, alt: false, ctrl: false, key }
}

const fn ctrl(key: &'static str) -> Shortcut {
    Shortcut { cmd: false, shift: false, alt: false, ctrl: true, key }
}

const fn ctrl_shift(key: &'static str) -> Shortcut {
    Shortcut { cmd: false, shift: true, alt: false, ctrl: true, key }
}

impl Shortcut {
    /// Whether a key press matches this shortcut.
    pub fn matches(&self, key: &str, cmd: bool, shift: bool, alt: bool, ctrl: bool) -> bool {
        self.key == key && self.cmd == cmd && self.shift == shift && self.alt == alt && self.ctrl == ctrl
    }

    /// The key as shown on a keycap.
    fn key_label(&self) -> String {
        match self.key {
            "space" => "Space".into(),
            "up" => "↑".into(),
            "down" => "↓".into(),
            "left" => "←".into(),
            "right" => "→".into(),
            k => k.to_uppercase(),
        }
    }

    /// The label split into keycaps: each modifier symbol, then the key.
    pub fn keycaps(&self) -> Vec<String> {
        let mut caps: Vec<String> = Vec::new();
        for (on, sym) in [(self.ctrl, "⌃"), (self.alt, "⌥"), (self.shift, "⇧"), (self.cmd, "⌘")] {
            if on {
                caps.push(sym.into());
            }
        }
        caps.push(self.key_label());
        caps
    }

    /// Accelerator string for the native menu.
    pub fn accelerator(&self) -> String {
        let mut parts = Vec::new();
        if self.ctrl {
            parts.push("Ctrl");
        }
        if self.alt {
            parts.push("Alt");
        }
        if self.shift {
            parts.push("Shift");
        }
        if self.cmd {
            parts.push("Cmd");
        }
        // muda's names ("UP", "SPACE", "I").
        let key = self.key.to_uppercase();
        parts.push(&key);
        parts.join("+")
    }
}

impl Command {
    pub const ALL: &[Command] = &[
        Command::NewFile,
        Command::OpenFolder,
        Command::OpenRecent,
        Command::InsertSnippet,
        Command::ClearRecent,
        Command::CloseFolder,
        Command::Quit,
        Command::Save,
        Command::CloseEditor,
        Command::ToggleSidebar,
        Command::TogglePanel,
        Command::ToggleAuxiliaryBar,
        Command::AssistantNewChat,
        Command::AssistantFocus,
        Command::OutlineFocus,
        Command::TimelineFocus,
        Command::ToggleMinimap,
        Command::ToggleWordWrap,
        Command::SplitEditor,
        Command::ShowExplorer,
        Command::ShowSearch,
        Command::ShowScm,
        Command::ShowDebug,
        Command::ShowExtensions,
        Command::ExtensionsInstallVsix,
        Command::ExtensionsInstallFromLocation,
        Command::ExtensionsOpenFolder,
        Command::ExtensionsCheckForUpdates,
        Command::ExtensionsUpdateAll,
        Command::RestartExtensionHost,
        Command::CheckForUpdates,
        Command::RestartToUpdate,
        Command::RestartLanguageServer,
        Command::StopLanguageServers,
        Command::FocusGroup1,
        Command::FocusGroup2,
        Command::FocusGroup3,
        Command::QuickOpen,
        Command::CommandPalette,
        Command::Undo,
        Command::Redo,
        Command::Cut,
        Command::Copy,
        Command::Paste,
        Command::SelectAll,
        Command::ToggleComment,
        Command::RefreshExplorer,
        Command::GoToDefinition,
        Command::Rename,
        Command::StartLinkedEditing,
        Command::GoToReferences,
        Command::GotoSymbol,
        Command::TriggerParameterHints,
        Command::ShowAllSymbols,
        Command::GotoLine,
        Command::QuickFix,
        Command::FormatDocument,
        Command::FormatSelection,
        Command::TriggerSuggest,
        Command::ToggleTerminal,
        Command::NewTerminal,
        Command::KillTerminal,
        Command::SplitTerminal,
        Command::FocusNextTerminal,
        Command::FocusPreviousTerminal,
        Command::FocusNextTerminalPane,
        Command::FocusPreviousTerminalPane,
        Command::ReplaceInFiles,
        Command::Find,
        Command::FindReplace,
        Command::FindNext,
        Command::FindPrevious,
        Command::GitCommit,
        Command::GitStageAll,
        Command::GitStageSelectedRanges,
        Command::GitUnstageSelectedRanges,
        Command::GitRevertSelectedRanges,
        Command::GitRefresh,
        Command::GitInit,
        Command::GitOpenChanges,
        Command::NextChange,
        Command::PreviousChange,
        Command::OpenSettings,
        Command::OpenKeybindings,
        Command::OpenKeybindingsFile,
        Command::KeepEditor,
        Command::OpenSettingsJson,
        Command::OpenWorkspaceSettingsJson,
        Command::SelectTheme,
        Command::InsertCursorAbove,
        Command::InsertCursorBelow,
        Command::InsertCursorAtLineEnds,
        Command::AddNextOccurrence,
        Command::AddPreviousOccurrence,
        Command::MoveToNextOccurrence,
        Command::SelectAllOccurrences,
        Command::JumpToBracket,
        Command::SelectToBracket,
        Command::Fold,
        Command::Unfold,
        Command::ToggleFold,
        Command::FoldRecursively,
        Command::UnfoldRecursively,
        Command::FoldAll,
        Command::UnfoldAll,
        Command::GitCheckout,
        Command::GitCheckoutDetached,
        Command::GitCreateBranch,
        Command::GitCreateBranchFrom,
        Command::GitRenameBranch,
        Command::GitDeleteBranch,
        Command::GitMerge,
        Command::GitAbortMerge,
        Command::GitRebase,
        Command::GitAbortRebase,
        Command::GitContinueRebase,
        Command::GitFetch,
        Command::GitFetchPrune,
        Command::GitFetchAll,
        Command::GitPull,
        Command::GitPullRebase,
        Command::GitPush,
        Command::GitPushForce,
        Command::GitSync,
        Command::GitPublish,
        Command::GitCommitAmend,
        Command::GitCommitPush,
        Command::GitCommitSync,
        Command::GitUndoCommit,
        Command::GitUnstageAll,
        Command::GitDiscardAll,
        Command::GitStash,
        Command::GitStashUntracked,
        Command::GitStashStaged,
        Command::GitStashPopLatest,
        Command::GitStashPop,
        Command::GitStashApplyLatest,
        Command::GitStashApply,
        Command::GitStashDrop,
        Command::GitStashDropAll,
        Command::GitAddRemote,
        Command::GitRemoveRemote,
        Command::GitCreateTag,
        Command::GitDeleteTag,
        Command::GitClone,
        Command::ConflictAcceptAllCurrent,
        Command::ConflictAcceptAllIncoming,
        Command::ConflictAcceptAllBoth,
        Command::ConflictNext,
        Command::ConflictPrevious,
        Command::DebugStart,
        Command::DebugRun,
        Command::DebugStop,
        Command::DebugRestart,
        Command::DebugContinue,
        Command::DebugPause,
        Command::DebugStepOver,
        Command::DebugStepInto,
        Command::DebugStepOut,
        Command::ToggleBreakpoint,
        Command::ConditionalBreakpoint,
        Command::AddLogpoint,
        Command::EnableAllBreakpoints,
        Command::DisableAllBreakpoints,
        Command::RemoveAllBreakpoints,
        Command::ToggleBreakpointsActivated,
        Command::DebugConfigure,
        Command::DebugSelectAndStart,
        Command::DebugAddWatch,
        Command::ToggleDebugConsole,
        Command::RunTask,
        Command::RunBuildTask,
        Command::TerminateTask,
        Command::ConfigureTasks,
        Command::ExplorerNewFile,
        Command::ExplorerNewFolder,
        Command::ExplorerRename,
        Command::ExplorerDelete,
        Command::CopyFilePath,
        Command::CopyRelativeFilePath,
        Command::RevealInFinder,
        Command::OpenInTerminal,
        Command::CollapseExplorerFolders,
        Command::SaveAs,
        Command::SaveAll,
        Command::RevertFile,
        Command::CloseOtherEditors,
        Command::CloseEditorsToTheRight,
        Command::CloseSavedEditors,
        Command::CloseGroupEditors,
        Command::CloseAllEditors,
        Command::RevealInExplorer,
        Command::SelectForCompare,
        Command::CompareWithSelected,
        Command::CompareWithSaved,
        Command::CompareFileWith,
        Command::PeekDefinition,
        Command::MarkdownPreview,
        Command::MarkdownPreviewSide,
        Command::ToggleZenMode,
        Command::ShowCallHierarchy,
        Command::ShowTypeHierarchy,
        Command::EmmetExpandAbbreviation,
        Command::EmmetWrapWithAbbreviation,
        Command::ChangeLanguageMode,
        Command::ShowTesting,
        Command::TestingRunAll,
        Command::TestingRunAtCursor,
        Command::TestingDebugAtCursor,
        Command::TestingRunCurrentFile,
        Command::TestingReRunLastRun,
        Command::TestingReRunFailed,
        Command::TestingCancel,
        Command::TestingRefresh,
        Command::TestingShowOutput,
        Command::TestingClearResults,
        Command::TestingCollapseAll,
        Command::NewSearchEditor,
        Command::NewSearchEditorToSide,
        Command::OpenSearchInEditor,
        Command::SearchEditorRerun,
        Command::SearchEditorToggleContext,
        Command::SearchEditorIncreaseContext,
        Command::SearchEditorDecreaseContext,
        Command::SearchEditorFocusInput,
        Command::SearchEditorDeleteFileResults,
        Command::SearchEditorSelectAllMatches,
        Command::GitOpenMergeEditor,
        Command::MergeNextConflict,
        Command::MergePreviousConflict,
        Command::MergeAcceptAllInput1,
        Command::MergeAcceptAllInput2,
        Command::MergeAcceptAllCombination,
        Command::MergeResetResult,
        Command::MergeComplete,
        Command::OpenWorkspaceFromFile,
        Command::AddFolderToWorkspace,
        Command::RemoveFolderFromWorkspace,
        Command::SaveWorkspaceAs,
    ];

    /// Stable identifier, matching the command ids where one exists.
    pub fn id(self) -> &'static str {
        match self {
            Command::Ext(i) => ext_command(i).id,
            Command::NewFile => "workbench.action.files.newUntitledFile",
            Command::OpenFolder => "workbench.action.files.openFolder",
            Command::OpenRecent => "workbench.action.openRecent",
            Command::InsertSnippet => "editor.action.insertSnippet",
            Command::ClearRecent => "workbench.action.clearRecentFiles",
            Command::CloseFolder => "workbench.action.closeFolder",
            Command::Quit => "workbench.action.quit",
            Command::Save => "workbench.action.files.save",
            Command::CloseEditor => "workbench.action.closeActiveEditor",
            Command::ToggleSidebar => "workbench.action.toggleSidebarVisibility",
            Command::TogglePanel => "workbench.action.togglePanel",
            Command::ToggleAuxiliaryBar => "workbench.action.toggleAuxiliaryBar",
            Command::AssistantNewChat => "orbvane.assistant.newChat",
            Command::AssistantFocus => "orbvane.assistant.focus",
            Command::OutlineFocus => "outline.focus",
            Command::TimelineFocus => "timeline.focus",
            Command::ToggleMinimap => "editor.action.toggleMinimap",
            Command::ToggleWordWrap => "editor.action.toggleWordWrap",
            Command::SplitEditor => "workbench.action.splitEditor",
            Command::ShowExplorer => "workbench.view.explorer",
            Command::ShowSearch => "workbench.view.search",
            Command::ShowScm => "workbench.view.scm",
            Command::ShowDebug => "workbench.view.debug",
            Command::ShowExtensions => "workbench.view.extensions",
            Command::ExtensionsInstallVsix => "workbench.extensions.action.installVSIX",
            Command::ExtensionsInstallFromLocation => "workbench.extensions.action.installExtensionFromLocation",
            Command::ExtensionsOpenFolder => "workbench.extensions.action.openExtensionsFolder",
            Command::ExtensionsCheckForUpdates => "workbench.extensions.action.checkForUpdates",
            Command::ExtensionsUpdateAll => "workbench.extensions.action.updateAllExtensions",
            Command::RestartExtensionHost => "workbench.action.restartExtensionHost",
            Command::CheckForUpdates => "update.checkForUpdate",
            Command::RestartToUpdate => "update.restartToUpdate",
            Command::RestartLanguageServer => "orbvane.languageServer.restart",
            Command::StopLanguageServers => "orbvane.languageServer.stopAll",
            Command::FocusGroup1 => "workbench.action.focusFirstEditorGroup",
            Command::FocusGroup2 => "workbench.action.focusSecondEditorGroup",
            Command::FocusGroup3 => "workbench.action.focusThirdEditorGroup",
            Command::QuickOpen => "workbench.action.quickOpen",
            Command::CommandPalette => "workbench.action.showCommands",
            Command::Undo => "undo",
            Command::Redo => "redo",
            Command::Cut => "editor.action.clipboardCutAction",
            Command::Copy => "editor.action.clipboardCopyAction",
            Command::Paste => "editor.action.clipboardPasteAction",
            Command::SelectAll => "editor.action.selectAll",
            Command::ToggleComment => "editor.action.commentLine",
            Command::RefreshExplorer => "workbench.files.action.refreshFilesExplorer",
            Command::GoToDefinition => "editor.action.revealDefinition",
            Command::Rename => "editor.action.rename",
            Command::StartLinkedEditing => "editor.action.linkedEditing",
            Command::GoToReferences => "editor.action.goToReferences",
            Command::GotoSymbol => "workbench.action.gotoSymbol",
            Command::TriggerParameterHints => "editor.action.triggerParameterHints",
            Command::ShowAllSymbols => "workbench.action.showAllSymbols",
            Command::GotoLine => "workbench.action.gotoLine",
            Command::QuickFix => "editor.action.quickFix",
            Command::FormatDocument => "editor.action.formatDocument",
            Command::FormatSelection => "editor.action.formatSelection",
            Command::TriggerSuggest => "editor.action.triggerSuggest",
            Command::ToggleTerminal => "workbench.action.terminal.toggleTerminal",
            Command::NewTerminal => "workbench.action.terminal.new",
            Command::KillTerminal => "workbench.action.terminal.kill",
            Command::SplitTerminal => "workbench.action.terminal.split",
            Command::FocusNextTerminal => "workbench.action.terminal.focusNext",
            Command::FocusPreviousTerminal => "workbench.action.terminal.focusPrevious",
            Command::FocusNextTerminalPane => "workbench.action.terminal.focusNextPane",
            Command::FocusPreviousTerminalPane => "workbench.action.terminal.focusPreviousPane",
            Command::ReplaceInFiles => "workbench.action.replaceInFiles",
            Command::Find => "actions.find",
            Command::FindReplace => "editor.action.startFindReplaceAction",
            Command::FindNext => "editor.action.nextMatchFindAction",
            Command::FindPrevious => "editor.action.previousMatchFindAction",
            Command::GitCommit => "git.commit",
            Command::GitStageAll => "git.stageAll",
            Command::GitStageSelectedRanges => "git.stageSelectedRanges",
            Command::GitUnstageSelectedRanges => "git.unstageSelectedRanges",
            Command::GitRevertSelectedRanges => "git.revertSelectedRanges",
            Command::GitRefresh => "git.refresh",
            Command::GitInit => "git.init",
            Command::GitOpenChanges => "git.openChange",
            Command::NextChange => "workbench.action.compareEditor.nextChange",
            Command::PreviousChange => "workbench.action.compareEditor.previousChange",
            Command::OpenSettings => "workbench.action.openSettings",
            Command::OpenKeybindings => "workbench.action.openGlobalKeybindings",
            Command::OpenKeybindingsFile => "workbench.action.openGlobalKeybindingsFile",
            Command::KeepEditor => "workbench.action.keepEditor",
            Command::OpenSettingsJson => "workbench.action.openSettingsJson",
            Command::OpenWorkspaceSettingsJson => "workbench.action.openWorkspaceSettingsFile",
            Command::SelectTheme => "workbench.action.selectTheme",
            Command::InsertCursorAbove => "editor.action.insertCursorAbove",
            Command::InsertCursorBelow => "editor.action.insertCursorBelow",
            Command::InsertCursorAtLineEnds => "editor.action.insertCursorAtEndOfEachLineSelected",
            Command::AddNextOccurrence => "editor.action.addSelectionToNextFindMatch",
            Command::AddPreviousOccurrence => "editor.action.addSelectionToPreviousFindMatch",
            Command::MoveToNextOccurrence => "editor.action.moveSelectionToNextFindMatch",
            Command::SelectAllOccurrences => "editor.action.selectHighlights",
            Command::JumpToBracket => "editor.action.jumpToBracket",
            Command::SelectToBracket => "editor.action.selectToBracket",
            Command::Fold => "editor.fold",
            Command::Unfold => "editor.unfold",
            Command::ToggleFold => "editor.toggleFold",
            Command::FoldRecursively => "editor.foldRecursively",
            Command::UnfoldRecursively => "editor.unfoldRecursively",
            Command::FoldAll => "editor.foldAll",
            Command::UnfoldAll => "editor.unfoldAll",
            Command::GitCheckout => "git.checkout",
            Command::GitCheckoutDetached => "git.checkoutDetached",
            Command::GitCreateBranch => "git.branch",
            Command::GitCreateBranchFrom => "git.branchFrom",
            Command::GitRenameBranch => "git.renameBranch",
            Command::GitDeleteBranch => "git.deleteBranch",
            Command::GitMerge => "git.merge",
            Command::GitAbortMerge => "git.mergeAbort",
            Command::GitRebase => "git.rebase",
            Command::GitAbortRebase => "git.rebaseAbort",
            Command::GitContinueRebase => "git.rebaseContinue",
            Command::GitFetch => "git.fetch",
            Command::GitFetchPrune => "git.fetchPrune",
            Command::GitFetchAll => "git.fetchAll",
            Command::GitPull => "git.pull",
            Command::GitPullRebase => "git.pullRebase",
            Command::GitPush => "git.push",
            Command::GitPushForce => "git.pushForce",
            Command::GitSync => "git.sync",
            Command::GitPublish => "git.publish",
            Command::GitCommitAmend => "git.commitStagedAmend",
            Command::GitCommitPush => "git.commitAllPush",
            Command::GitCommitSync => "git.commitAllSync",
            Command::GitUndoCommit => "git.undoCommit",
            Command::GitUnstageAll => "git.unstageAll",
            Command::GitDiscardAll => "git.cleanAll",
            Command::GitStash => "git.stash",
            Command::GitStashUntracked => "git.stashIncludeUntracked",
            Command::GitStashStaged => "git.stashStaged",
            Command::GitStashPopLatest => "git.stashPopLatest",
            Command::GitStashPop => "git.stashPop",
            Command::GitStashApplyLatest => "git.stashApplyLatest",
            Command::GitStashApply => "git.stashApply",
            Command::GitStashDrop => "git.stashDrop",
            Command::GitStashDropAll => "git.stashDropAll",
            Command::GitAddRemote => "git.addRemote",
            Command::GitRemoveRemote => "git.removeRemote",
            Command::GitCreateTag => "git.createTag",
            Command::GitDeleteTag => "git.deleteTag",
            Command::GitClone => "git.clone",
            Command::ConflictAcceptAllCurrent => "merge-conflict.accept.all-current",
            Command::ConflictAcceptAllIncoming => "merge-conflict.accept.all-incoming",
            Command::ConflictAcceptAllBoth => "merge-conflict.accept.all-both",
            Command::ConflictNext => "merge-conflict.next",
            Command::ConflictPrevious => "merge-conflict.previous",
            Command::DebugStart => "workbench.action.debug.start",
            Command::DebugRun => "workbench.action.debug.run",
            Command::DebugStop => "workbench.action.debug.stop",
            Command::DebugRestart => "workbench.action.debug.restart",
            Command::DebugContinue => "workbench.action.debug.continue",
            Command::DebugPause => "workbench.action.debug.pause",
            Command::DebugStepOver => "workbench.action.debug.stepOver",
            Command::DebugStepInto => "workbench.action.debug.stepInto",
            Command::DebugStepOut => "workbench.action.debug.stepOut",
            Command::ToggleBreakpoint => "editor.debug.action.toggleBreakpoint",
            Command::ConditionalBreakpoint => "editor.debug.action.conditionalBreakpoint",
            Command::AddLogpoint => "editor.debug.action.addLogPoint",
            Command::EnableAllBreakpoints => "workbench.debug.viewlet.action.enableAllBreakpoints",
            Command::DisableAllBreakpoints => "workbench.debug.viewlet.action.disableAllBreakpoints",
            Command::RemoveAllBreakpoints => "workbench.debug.viewlet.action.removeAllBreakpoints",
            Command::ToggleBreakpointsActivated => "workbench.debug.viewlet.action.toggleBreakpointsActivatedAction",
            Command::DebugConfigure => "workbench.action.debug.configure",
            Command::DebugSelectAndStart => "workbench.action.debug.selectandstart",
            Command::DebugAddWatch => "workbench.debug.viewlet.action.addWatchExpression",
            Command::ToggleDebugConsole => "workbench.debug.action.toggleRepl",
            Command::RunTask => "workbench.action.tasks.runTask",
            Command::RunBuildTask => "workbench.action.tasks.build",
            Command::TerminateTask => "workbench.action.tasks.terminate",
            Command::ConfigureTasks => "workbench.action.tasks.configureTaskRunner",
            Command::ExplorerNewFile => "explorer.newFile",
            Command::ExplorerNewFolder => "explorer.newFolder",
            Command::ExplorerRename => "renameFile",
            Command::ExplorerDelete => "moveFileToTrash",
            Command::CopyFilePath => "copyFilePath",
            Command::CopyRelativeFilePath => "copyRelativeFilePath",
            Command::RevealInFinder => "revealFileInOS",
            Command::OpenInTerminal => "openInIntegratedTerminal",
            Command::CollapseExplorerFolders => "workbench.files.action.collapseExplorerFolders",
            Command::SaveAs => "workbench.action.files.saveAs",
            Command::SaveAll => "workbench.action.files.saveAll",
            Command::RevertFile => "workbench.action.files.revert",
            Command::CloseOtherEditors => "workbench.action.closeOtherEditors",
            Command::CloseEditorsToTheRight => "workbench.action.closeEditorsToTheRight",
            Command::CloseSavedEditors => "workbench.action.closeUnmodifiedEditors",
            Command::CloseGroupEditors => "workbench.action.closeEditorsInGroup",
            Command::CloseAllEditors => "workbench.action.closeAllEditors",
            Command::RevealInExplorer => "workbench.files.action.showActiveFileInExplorer",
            Command::SelectForCompare => "selectForCompare",
            Command::CompareWithSelected => "compareSelected",
            Command::CompareWithSaved => "workbench.files.action.compareWithSaved",
            Command::CompareFileWith => "workbench.files.action.compareFileWith",
            Command::PeekDefinition => "editor.action.peekDefinition",
            Command::MarkdownPreview => "markdown.showPreview",
            Command::MarkdownPreviewSide => "markdown.showPreviewToSide",
            Command::ToggleZenMode => "workbench.action.toggleZenMode",
            Command::ShowCallHierarchy => "editor.showCallHierarchy",
            Command::ShowTypeHierarchy => "editor.showTypeHierarchy",
            Command::EmmetExpandAbbreviation => "editor.emmet.action.expandAbbreviation",
            Command::EmmetWrapWithAbbreviation => "editor.emmet.action.wrapWithAbbreviation",
            Command::ChangeLanguageMode => "workbench.action.editor.changeLanguageMode",
            Command::ShowTesting => "workbench.view.testing",
            Command::TestingRunAll => "testing.runAll",
            Command::TestingRunAtCursor => "testing.runAtCursor",
            Command::TestingDebugAtCursor => "testing.debugAtCursor",
            Command::TestingRunCurrentFile => "testing.runCurrentFile",
            Command::TestingReRunLastRun => "testing.reRunLastRun",
            Command::TestingReRunFailed => "testing.reRunFailTests",
            Command::TestingCancel => "testing.cancelRun",
            Command::TestingRefresh => "testing.refreshTests",
            Command::TestingShowOutput => "testing.showMostRecentOutput",
            Command::TestingClearResults => "testing.clearTestResults",
            Command::TestingCollapseAll => "testing.collapseAll",
            Command::NewSearchEditor => "search.action.openNewEditor",
            Command::NewSearchEditorToSide => "search.action.openNewEditorToSide",
            Command::OpenSearchInEditor => "search.action.openInEditor",
            Command::SearchEditorRerun => "rerunSearchEditorSearch",
            Command::SearchEditorToggleContext => "toggleSearchEditorContextLines",
            Command::SearchEditorIncreaseContext => "increaseSearchEditorContextLines",
            Command::SearchEditorDecreaseContext => "decreaseSearchEditorContextLines",
            Command::SearchEditorFocusInput => "search.action.focusQueryEditorWidget",
            Command::SearchEditorDeleteFileResults => "search.searchEditor.action.deleteFileResults",
            Command::SearchEditorSelectAllMatches => "selectAllSearchEditorMatches",
            Command::GitOpenMergeEditor => "git.openMergeEditor",
            Command::MergeNextConflict => "merge.goToNextUnhandledConflict",
            Command::MergePreviousConflict => "merge.goToPreviousUnhandledConflict",
            Command::MergeAcceptAllInput1 => "merge.acceptAllInput1",
            Command::MergeAcceptAllInput2 => "merge.acceptAllInput2",
            Command::MergeAcceptAllCombination => "mergeEditor.acceptAllCombination",
            Command::MergeResetResult => "mergeEditor.resetResultToBaseAndAutoMerge",
            Command::MergeComplete => "mergeEditor.acceptMerge",
            Command::OpenWorkspaceFromFile => "workbench.action.openWorkspace",
            Command::AddFolderToWorkspace => "workbench.action.addRootFolder",
            Command::RemoveFolderFromWorkspace => "workbench.action.removeRootFolder",
            Command::SaveWorkspaceAs => "workbench.action.saveWorkspaceAs",
        }
    }

    /// Whether the command needs a git repository (hidden from the palette without one).
    pub fn needs_repo(self) -> bool {
        self.id().starts_with("git.") && !matches!(self, Command::GitInit | Command::GitClone)
    }

    pub fn from_id(id: &str) -> Option<Command> {
        Command::ALL.iter().copied().find(|c| c.id() == id).or_else(|| ext_command_named(id))
    }

    /// The built-in commands and the enabled extensions' palette commands.
    pub fn all() -> Vec<Command> {
        let mut all = Command::ALL.to_vec();
        EXT_COMMANDS.with(|e| all.extend(e.borrow().iter().enumerate().filter(|(_, c)| c.enabled && c.in_palette).map(|(i, _)| Command::Ext(i as u16))));
        all
    }

    /// Title shown in the command palette.
    pub fn title(self) -> &'static str {
        match self {
            Command::Ext(i) => ext_command(i).title,
            Command::NewFile => "File: New Untitled Text File",
            Command::OpenFolder => "File: Open Folder...",
            Command::OpenRecent => "File: Open Recent...",
            Command::InsertSnippet => "Snippets: Insert Snippet",
            Command::ClearRecent => "File: Clear Recently Opened...",
            Command::CloseFolder => "Workspaces: Close Folder",
            Command::Quit => "Quit",
            Command::Save => "File: Save",
            Command::CloseEditor => "View: Close Editor",
            Command::ToggleSidebar => "View: Toggle Primary Side Bar Visibility",
            Command::TogglePanel => "View: Toggle Panel Visibility",
            Command::ToggleAuxiliaryBar => "View: Toggle Secondary Side Bar Visibility",
            Command::AssistantNewChat => "Assistant: New Chat",
            Command::AssistantFocus => "Assistant: Ask the Agent",
            Command::OutlineFocus => "Outline: Focus on Outline View",
            Command::TimelineFocus => "Timeline: Focus on Timeline View",
            Command::ToggleMinimap => "View: Toggle Minimap",
            Command::ToggleWordWrap => "View: Toggle Word Wrap",
            Command::SplitEditor => "View: Split Editor",
            Command::ShowExplorer => "View: Show Explorer",
            Command::ShowSearch => "View: Show Search",
            Command::ShowScm => "View: Show Source Control",
            Command::ShowDebug => "View: Show Run and Debug",
            Command::ShowExtensions => "View: Show Extensions",
            Command::ExtensionsInstallVsix => "Extensions: Install from VSIX...",
            Command::ExtensionsInstallFromLocation => "Developer: Install Extension from Location...",
            Command::ExtensionsOpenFolder => "Extensions: Open Extensions Folder",
            Command::ExtensionsCheckForUpdates => "Extensions: Check for Extension Updates",
            Command::ExtensionsUpdateAll => "Extensions: Update All Extensions",
            Command::RestartExtensionHost => "Developer: Restart Extension Host",
            Command::CheckForUpdates => "Check for Updates...",
            Command::RestartToUpdate => "Restart to Update",
            Command::RestartLanguageServer => "Developer: Restart Language Server",
            Command::StopLanguageServers => "Developer: Stop Language Servers",
            Command::FocusGroup1 => "View: Focus First Editor Group",
            Command::FocusGroup2 => "View: Focus Second Editor Group",
            Command::FocusGroup3 => "View: Focus Third Editor Group",
            Command::QuickOpen => "Go to File...",
            Command::CommandPalette => "Show All Commands",
            Command::Undo => "Undo",
            Command::Redo => "Redo",
            Command::Cut => "Cut",
            Command::Copy => "Copy",
            Command::Paste => "Paste",
            Command::SelectAll => "Select All",
            Command::ToggleComment => "Toggle Line Comment",
            Command::RefreshExplorer => "File: Refresh Explorer",
            Command::GoToDefinition => "Go to Definition",
            Command::Rename => "Rename Symbol",
            Command::StartLinkedEditing => "Start Linked Editing",
            Command::GoToReferences => "Go to References",
            Command::GotoSymbol => "Go to Symbol in Editor...",
            Command::TriggerParameterHints => "Trigger Parameter Hints",
            Command::ShowAllSymbols => "Go to Symbol in Workspace...",
            Command::GotoLine => "Go to Line/Column...",
            Command::QuickFix => "Quick Fix...",
            Command::FormatDocument => "Format Document",
            Command::FormatSelection => "Format Selection",
            Command::TriggerSuggest => "Trigger Suggest",
            Command::ToggleTerminal => "View: Toggle Terminal",
            Command::NewTerminal => "Terminal: Create New Terminal",
            Command::KillTerminal => "Terminal: Kill the Active Terminal Instance",
            Command::SplitTerminal => "Terminal: Split Terminal",
            Command::FocusNextTerminal => "Terminal: Focus Next Terminal Group",
            Command::FocusPreviousTerminal => "Terminal: Focus Previous Terminal Group",
            Command::FocusNextTerminalPane => "Terminal: Focus Next Terminal in Terminal Group",
            Command::FocusPreviousTerminalPane => "Terminal: Focus Previous Terminal in Terminal Group",
            Command::ReplaceInFiles => "Search: Replace in Files",
            Command::Find => "Find",
            Command::FindReplace => "Replace",
            Command::FindNext => "Find Next",
            Command::FindPrevious => "Find Previous",
            Command::GitCommit => "Git: Commit",
            Command::GitStageAll => "Git: Stage All Changes",
            Command::GitStageSelectedRanges => "Git: Stage Selected Ranges",
            Command::GitUnstageSelectedRanges => "Git: Unstage Selected Ranges",
            Command::GitRevertSelectedRanges => "Git: Revert Selected Ranges",
            Command::GitRefresh => "Git: Refresh",
            Command::GitInit => "Git: Initialize Repository",
            Command::GitOpenChanges => "Git: Open Changes",
            Command::NextChange => "Go to Next Difference",
            Command::PreviousChange => "Go to Previous Difference",
            Command::OpenSettings => "Preferences: Open Settings (UI)",
            Command::OpenKeybindings => "Preferences: Open Keyboard Shortcuts",
            Command::OpenKeybindingsFile => "Preferences: Open Keyboard Shortcuts (JSON)",
            Command::KeepEditor => "View: Keep Editor",
            Command::OpenSettingsJson => "Preferences: Open User Settings (JSON)",
            Command::OpenWorkspaceSettingsJson => "Preferences: Open Workspace Settings (JSON)",
            Command::SelectTheme => "Preferences: Color Theme",
            Command::InsertCursorAbove => "Add Cursor Above",
            Command::InsertCursorBelow => "Add Cursor Below",
            Command::InsertCursorAtLineEnds => "Add Cursors to Line Ends",
            Command::AddNextOccurrence => "Add Selection To Next Find Match",
            Command::AddPreviousOccurrence => "Add Selection To Previous Find Match",
            Command::MoveToNextOccurrence => "Move Last Selection To Next Find Match",
            Command::SelectAllOccurrences => "Select All Occurrences of Find Match",
            Command::JumpToBracket => "Go to Bracket",
            Command::SelectToBracket => "Select to Bracket",
            Command::Fold => "Fold",
            Command::Unfold => "Unfold",
            Command::ToggleFold => "Toggle Fold",
            Command::FoldRecursively => "Fold Recursively",
            Command::UnfoldRecursively => "Unfold Recursively",
            Command::FoldAll => "Fold All",
            Command::UnfoldAll => "Unfold All",
            Command::GitCheckout => "Git: Checkout to...",
            Command::GitCheckoutDetached => "Git: Checkout to (Detached)...",
            Command::GitCreateBranch => "Git: Create Branch...",
            Command::GitCreateBranchFrom => "Git: Create Branch From...",
            Command::GitRenameBranch => "Git: Rename Branch...",
            Command::GitDeleteBranch => "Git: Delete Branch...",
            Command::GitMerge => "Git: Merge...",
            Command::GitAbortMerge => "Git: Abort Merge",
            Command::GitRebase => "Git: Rebase Branch...",
            Command::GitAbortRebase => "Git: Abort Rebase",
            Command::GitContinueRebase => "Git: Continue Rebase",
            Command::GitFetch => "Git: Fetch",
            Command::GitFetchPrune => "Git: Fetch (Prune)",
            Command::GitFetchAll => "Git: Fetch From All Remotes",
            Command::GitPull => "Git: Pull",
            Command::GitPullRebase => "Git: Pull (Rebase)",
            Command::GitPush => "Git: Push",
            Command::GitPushForce => "Git: Push (Force)",
            Command::GitSync => "Git: Sync",
            Command::GitPublish => "Git: Publish Branch...",
            Command::GitCommitAmend => "Git: Commit Staged (Amend)",
            Command::GitCommitPush => "Git: Commit & Push",
            Command::GitCommitSync => "Git: Commit & Sync",
            Command::GitUndoCommit => "Git: Undo Last Commit",
            Command::GitUnstageAll => "Git: Unstage All Changes",
            Command::GitDiscardAll => "Git: Discard All Changes",
            Command::GitStash => "Git: Stash",
            Command::GitStashUntracked => "Git: Stash (Include Untracked)",
            Command::GitStashStaged => "Git: Stash Staged",
            Command::GitStashPopLatest => "Git: Pop Latest Stash",
            Command::GitStashPop => "Git: Pop Stash...",
            Command::GitStashApplyLatest => "Git: Apply Latest Stash",
            Command::GitStashApply => "Git: Apply Stash...",
            Command::GitStashDrop => "Git: Drop Stash...",
            Command::GitStashDropAll => "Git: Drop All Stashes...",
            Command::GitAddRemote => "Git: Add Remote...",
            Command::GitRemoveRemote => "Git: Remove Remote",
            Command::GitCreateTag => "Git: Create Tag",
            Command::GitDeleteTag => "Git: Delete Tag",
            Command::GitClone => "Git: Clone",
            Command::ConflictAcceptAllCurrent => "Merge Conflict: Accept All Current",
            Command::ConflictAcceptAllIncoming => "Merge Conflict: Accept All Incoming",
            Command::ConflictAcceptAllBoth => "Merge Conflict: Accept All Both",
            Command::ConflictNext => "Merge Conflict: Next Conflict",
            Command::ConflictPrevious => "Merge Conflict: Previous Conflict",
            Command::DebugStart => "Debug: Start Debugging",
            Command::DebugRun => "Debug: Run Without Debugging",
            Command::DebugStop => "Debug: Stop",
            Command::DebugRestart => "Debug: Restart",
            Command::DebugContinue => "Debug: Continue",
            Command::DebugPause => "Debug: Pause",
            Command::DebugStepOver => "Debug: Step Over",
            Command::DebugStepInto => "Debug: Step Into",
            Command::DebugStepOut => "Debug: Step Out",
            Command::ToggleBreakpoint => "Debug: Toggle Breakpoint",
            Command::ConditionalBreakpoint => "Debug: Add Conditional Breakpoint...",
            Command::AddLogpoint => "Debug: Add Logpoint...",
            Command::EnableAllBreakpoints => "Debug: Enable All Breakpoints",
            Command::DisableAllBreakpoints => "Debug: Disable All Breakpoints",
            Command::RemoveAllBreakpoints => "Debug: Remove All Breakpoints",
            Command::ToggleBreakpointsActivated => "Debug: Toggle Activate Breakpoints",
            Command::DebugConfigure => "Debug: Open 'launch.json'",
            Command::DebugSelectAndStart => "Debug: Select and Start Debugging",
            Command::DebugAddWatch => "Debug: Add to Watch",
            Command::ToggleDebugConsole => "View: Toggle Debug Console",
            Command::RunTask => "Tasks: Run Task",
            Command::RunBuildTask => "Tasks: Run Build Task",
            Command::TerminateTask => "Tasks: Terminate Task",
            Command::ConfigureTasks => "Tasks: Configure Task",
            Command::ExplorerNewFile => "File: New File...",
            Command::ExplorerNewFolder => "File: New Folder...",
            Command::ExplorerRename => "File: Rename...",
            Command::ExplorerDelete => "File: Delete",
            Command::CopyFilePath => "File: Copy Path of Active File",
            Command::CopyRelativeFilePath => "File: Copy Relative Path of Active File",
            Command::RevealInFinder => "File: Reveal in Finder",
            Command::OpenInTerminal => "File: Open in Integrated Terminal",
            Command::CollapseExplorerFolders => "File: Collapse Folders in Explorer",
            Command::SaveAs => "File: Save As...",
            Command::SaveAll => "File: Save All",
            Command::RevertFile => "File: Revert File",
            Command::CloseOtherEditors => "View: Close Other Editors in Group",
            Command::CloseEditorsToTheRight => "View: Close Editors to the Right in Group",
            Command::CloseSavedEditors => "View: Close Saved Editors in Group",
            Command::CloseGroupEditors => "View: Close All Editors in Group",
            Command::CloseAllEditors => "View: Close All Editors",
            Command::RevealInExplorer => "File: Reveal Active File in Explorer View",
            Command::SelectForCompare => "File: Select for Compare",
            Command::CompareWithSelected => "File: Compare with Selected",
            Command::CompareWithSaved => "File: Compare Active File with Saved",
            Command::CompareFileWith => "File: Compare Active File With...",
            Command::PeekDefinition => "Peek Definition",
            Command::MarkdownPreview => "Markdown: Open Preview",
            Command::MarkdownPreviewSide => "Markdown: Open Preview to the Side",
            Command::ToggleZenMode => "View: Toggle Zen Mode",
            Command::ShowCallHierarchy => "Peek Call Hierarchy",
            Command::ShowTypeHierarchy => "Peek Type Hierarchy",
            Command::EmmetExpandAbbreviation => "Emmet: Expand Abbreviation",
            Command::EmmetWrapWithAbbreviation => "Emmet: Wrap with Abbreviation",
            Command::ChangeLanguageMode => "Change Language Mode",
            Command::ShowTesting => "View: Show Testing",
            Command::TestingRunAll => "Test: Run All Tests",
            Command::TestingRunAtCursor => "Test: Run Test at Cursor",
            Command::TestingDebugAtCursor => "Test: Debug Test at Cursor",
            Command::TestingRunCurrentFile => "Test: Run Tests in Current File",
            Command::TestingReRunLastRun => "Test: Rerun Last Run",
            Command::TestingReRunFailed => "Test: Rerun Failed Tests",
            Command::TestingCancel => "Test: Cancel Test Run",
            Command::TestingRefresh => "Test: Refresh Tests",
            Command::TestingShowOutput => "Test: Show Output",
            Command::TestingClearResults => "Test: Clear All Results",
            Command::TestingCollapseAll => "Test: Collapse All Tests",
            Command::NewSearchEditor => "Search Editor: New Search Editor",
            Command::NewSearchEditorToSide => "Search Editor: Open New Search Editor to the Side",
            Command::OpenSearchInEditor => "Search Editor: Open Results in Editor",
            Command::SearchEditorRerun => "Search Editor: Search Again",
            Command::SearchEditorToggleContext => "Search Editor: Toggle Context Lines",
            Command::SearchEditorIncreaseContext => "Search Editor: Increase Context Lines",
            Command::SearchEditorDecreaseContext => "Search Editor: Decrease Context Lines",
            Command::SearchEditorFocusInput => "Search Editor: Focus Search Editor Input",
            Command::SearchEditorDeleteFileResults => "Search Editor: Delete File Results",
            Command::SearchEditorSelectAllMatches => "Search Editor: Select All Matches",
            Command::GitOpenMergeEditor => "Git: Resolve in Merge Editor",
            Command::MergeNextConflict => "Merge Editor: Go to Next Unhandled Conflict",
            Command::MergePreviousConflict => "Merge Editor: Go to Previous Unhandled Conflict",
            Command::MergeAcceptAllInput1 => "Merge Editor: Accept All Incoming Changes from Left",
            Command::MergeAcceptAllInput2 => "Merge Editor: Accept All Current Changes from Right",
            Command::MergeAcceptAllCombination => "Merge Editor: Accept All Combination",
            Command::MergeResetResult => "Merge Editor: Reset Result",
            Command::MergeComplete => "Merge Editor: Complete Merge",
            Command::OpenWorkspaceFromFile => "File: Open Workspace from File...",
            Command::AddFolderToWorkspace => "Workspaces: Add Folder to Workspace...",
            Command::RemoveFolderFromWorkspace => "Workspaces: Remove Folder from Workspace...",
            Command::SaveWorkspaceAs => "Workspaces: Save Workspace As...",
        }
    }

    /// Short label for native menu items.
    pub fn menu_label(self) -> &'static str {
        match self {
            Command::NewFile => "New Text File",
            Command::OpenFolder => "Open Folder...",
            Command::OpenRecent => "More...",
            Command::ClearRecent => "Clear Recently Opened...",
            Command::CloseFolder => "Close Folder",
            Command::Quit => "Quit orbvane",
            Command::Save => "Save",
            Command::CloseEditor => "Close Editor",
            Command::ToggleSidebar => "Primary Side Bar",
            Command::TogglePanel => "Panel",
            Command::ToggleAuxiliaryBar => "Secondary Side Bar",
            Command::AssistantNewChat => "New Chat",
            Command::AssistantFocus => "Assistant",
            Command::OutlineFocus => "Outline",
            Command::TimelineFocus => "Timeline",
            Command::ToggleMinimap => "Minimap",
            Command::ToggleWordWrap => "Word Wrap",
            Command::SplitEditor => "Split Editor",
            Command::ShowExplorer => "Explorer",
            Command::ShowSearch => "Search",
            Command::ShowScm => "Source Control",
            Command::ShowDebug => "Run and Debug",
            Command::ShowExtensions => "Extensions",
            Command::ExtensionsInstallVsix => "Install from VSIX...",
            Command::ExtensionsInstallFromLocation => "Install Extension from Location...",
            Command::ExtensionsOpenFolder => "Open Extensions Folder",
            Command::ExtensionsCheckForUpdates => "Check for Extension Updates",
            Command::ExtensionsUpdateAll => "Update All Extensions",
            Command::RestartExtensionHost => "Restart Extensions",
            Command::CheckForUpdates => "Check for Updates...",
            Command::RestartToUpdate => "Restart to Update",
            Command::QuickOpen => "Go to File...",
            Command::CommandPalette => "Command Palette...",
            Command::ToggleComment => "Toggle Line Comment",
            Command::RefreshExplorer => "Refresh Explorer",
            Command::ToggleTerminal => "Terminal",
            Command::NewTerminal => "New Terminal",
            Command::KillTerminal => "Kill Terminal",
            Command::SplitTerminal => "Split Terminal",
            Command::ReplaceInFiles => "Replace in Files",
            Command::OpenSettings => "Settings",
            Command::OpenKeybindings => "Keyboard Shortcuts",
            Command::SelectTheme => "Color Theme",
            Command::AddNextOccurrence => "Add Next Occurrence",
            Command::AddPreviousOccurrence => "Add Previous Occurrence",
            Command::SelectAllOccurrences => "Select All Occurrences",
            Command::DebugStart => "Start Debugging",
            Command::DebugRun => "Run Without Debugging",
            Command::DebugStop => "Stop Debugging",
            Command::DebugRestart => "Restart Debugging",
            Command::DebugContinue => "Continue",
            Command::DebugPause => "Pause",
            Command::DebugStepOver => "Step Over",
            Command::DebugStepInto => "Step Into",
            Command::DebugStepOut => "Step Out",
            Command::ToggleBreakpoint => "Toggle Breakpoint",
            Command::ConditionalBreakpoint => "Conditional Breakpoint...",
            Command::AddLogpoint => "Logpoint...",
            Command::EnableAllBreakpoints => "Enable All Breakpoints",
            Command::DisableAllBreakpoints => "Disable All Breakpoints",
            Command::RemoveAllBreakpoints => "Remove All Breakpoints",
            Command::ToggleBreakpointsActivated => "Toggle Activate Breakpoints",
            Command::DebugConfigure => "Open Configurations",
            Command::DebugSelectAndStart => "Select and Start Debugging...",
            Command::DebugAddWatch => "Add Watch Expression",
            Command::ToggleDebugConsole => "Debug Console",
            Command::RunTask => "Run Task...",
            Command::RunBuildTask => "Run Build Task...",
            Command::TerminateTask => "Terminate Task...",
            Command::ConfigureTasks => "Configure Tasks...",
            Command::ExplorerNewFile => "New File...",
            Command::ExplorerNewFolder => "New Folder...",
            Command::ExplorerRename => "Rename...",
            Command::ExplorerDelete => "Delete",
            Command::CopyFilePath => "Copy Path",
            Command::CopyRelativeFilePath => "Copy Relative Path",
            Command::RevealInFinder => "Reveal in Finder",
            Command::OpenInTerminal => "Open in Integrated Terminal",
            Command::CollapseExplorerFolders => "Collapse Folders in Explorer",
            Command::SaveAs => "Save As...",
            Command::SaveAll => "Save All",
            Command::RevertFile => "Revert File",
            Command::CloseOtherEditors => "Close Others",
            Command::CloseEditorsToTheRight => "Close to the Right",
            Command::CloseSavedEditors => "Close Saved",
            Command::CloseGroupEditors => "Close All Editors in Group",
            Command::CloseAllEditors => "Close All",
            Command::RevealInExplorer => "Reveal in Explorer View",
            Command::SelectForCompare => "Select for Compare",
            Command::CompareWithSelected => "Compare with Selected",
            Command::CompareWithSaved => "Compare with Saved",
            Command::CompareFileWith => "Compare Active File With...",
            Command::PeekDefinition => "Peek Definition",
            Command::MarkdownPreview => "Open Preview",
            Command::MarkdownPreviewSide => "Open Preview to the Side",
            Command::ToggleZenMode => "Zen Mode",
            Command::ShowCallHierarchy => "Peek Call Hierarchy",
            Command::ShowTypeHierarchy => "Peek Type Hierarchy",
            Command::ShowTesting => "Testing",
            Command::NewSearchEditor => "New Search Editor",
            Command::OpenWorkspaceFromFile => "Open Workspace from File...",
            Command::AddFolderToWorkspace => "Add Folder to Workspace...",
            Command::RemoveFolderFromWorkspace => "Remove Folder from Workspace",
            Command::SaveWorkspaceAs => "Save Workspace As...",
            // Git commands in menus drop the "Git: " category in the "..." menu.
            other => other.title().strip_prefix("Git: ").unwrap_or(other.title()),
        }
    }

    pub fn shortcut(self) -> Option<Shortcut> {
        Some(match self {
            Command::NewFile => cmd("n"),
            Command::OpenFolder => cmd("o"),
            Command::OpenRecent => ctrl("r"),
            Command::Save => cmd("s"),
            Command::ToggleWordWrap => Shortcut { cmd: false, shift: false, alt: true, ctrl: false, key: "z" },
            Command::Quit => cmd("q"),
            Command::CloseEditor => cmd("w"),
            Command::ToggleSidebar => cmd("b"),
            Command::TogglePanel => cmd("j"),
            Command::ToggleAuxiliaryBar => Shortcut { cmd: true, shift: false, alt: true, ctrl: false, key: "b" },
            Command::AssistantFocus => cmd_shift("i"),
            Command::SplitEditor => cmd("\\"),
            Command::ShowExplorer => cmd_shift("e"),
            Command::ShowSearch => cmd_shift("f"),
            Command::ShowScm => ctrl_shift("g"),
            Command::ShowDebug => cmd_shift("d"),
            Command::ShowExtensions => cmd_shift("x"),
            Command::FocusGroup1 => cmd("1"),
            Command::FocusGroup2 => cmd("2"),
            Command::FocusGroup3 => cmd("3"),
            Command::QuickOpen => cmd("p"),
            Command::CommandPalette => cmd_shift("p"),
            Command::Undo => cmd("z"),
            Command::Redo => cmd_shift("z"),
            Command::Cut => cmd("x"),
            Command::Copy => cmd("c"),
            Command::Paste => cmd("v"),
            Command::SelectAll => cmd("a"),
            Command::ToggleComment => cmd("/"),
            Command::GoToDefinition => plain("f12"),
            Command::Rename => plain("f2"),
            Command::StartLinkedEditing => Shortcut { cmd: true, shift: true, alt: false, ctrl: false, key: "f2" },
            Command::QuickFix => cmd("."),
            Command::FormatDocument => Shortcut { cmd: false, shift: true, alt: true, ctrl: false, key: "f" },
            Command::GoToReferences => Shortcut { cmd: false, shift: true, alt: false, ctrl: false, key: "f12" },
            Command::GotoSymbol => cmd_shift("o"),
            Command::TriggerParameterHints => cmd_shift("space"),
            Command::ShowAllSymbols => cmd("t"),
            Command::GotoLine => ctrl("g"),
            Command::TriggerSuggest => ctrl("space"),
            Command::ToggleTerminal => ctrl("`"),
            Command::NewTerminal => ctrl_shift("`"),
            Command::ReplaceInFiles => cmd_shift("h"),
            Command::Find => cmd("f"),
            Command::FindReplace => Shortcut { cmd: true, shift: false, alt: true, ctrl: false, key: "f" },
            Command::FindNext => cmd("g"),
            Command::FindPrevious => cmd_shift("g"),
            Command::NextChange => plain("f7"),
            Command::PreviousChange => Shortcut { cmd: false, shift: true, alt: false, ctrl: false, key: "f7" },
            Command::OpenSettings => cmd(","),
            Command::InsertCursorAbove => Shortcut { cmd: true, shift: false, alt: true, ctrl: false, key: "up" },
            Command::InsertCursorBelow => Shortcut { cmd: true, shift: false, alt: true, ctrl: false, key: "down" },
            Command::InsertCursorAtLineEnds => Shortcut { cmd: false, shift: true, alt: true, ctrl: false, key: "i" },
            Command::AddNextOccurrence => cmd("d"),
            Command::SelectAllOccurrences => cmd_shift("l"),
            Command::JumpToBracket => cmd_shift("\\"),
            Command::Fold => Shortcut { cmd: true, shift: false, alt: true, ctrl: false, key: "[" },
            Command::Unfold => Shortcut { cmd: true, shift: false, alt: true, ctrl: false, key: "]" },
            Command::DebugStart => plain("f5"),
            Command::DebugRun => ctrl("f5"),
            Command::DebugStop => Shortcut { cmd: false, shift: true, alt: false, ctrl: false, key: "f5" },
            Command::DebugRestart => cmd_shift("f5"),
            Command::DebugPause => plain("f6"),
            Command::DebugStepOver => plain("f10"),
            Command::DebugStepInto => plain("f11"),
            Command::DebugStepOut => Shortcut { cmd: false, shift: true, alt: false, ctrl: false, key: "f11" },
            Command::ToggleBreakpoint => plain("f9"),
            Command::ToggleDebugConsole => cmd_shift("y"),
            Command::RunBuildTask => cmd_shift("b"),
            Command::MarkdownPreview => cmd_shift("v"),
            Command::ShowCallHierarchy => Shortcut { cmd: false, shift: true, alt: true, ctrl: false, key: "h" },
            Command::PeekDefinition => Shortcut { cmd: false, shift: false, alt: true, ctrl: false, key: "f12" },
            Command::SaveAs => cmd_shift("s"),
            Command::SaveAll => Shortcut { cmd: true, shift: false, alt: true, ctrl: false, key: "s" },
            Command::CloseOtherEditors => Shortcut { cmd: true, shift: false, alt: true, ctrl: false, key: "t" },
            Command::CopyFilePath => Shortcut { cmd: true, shift: false, alt: true, ctrl: false, key: "c" },
            Command::CopyRelativeFilePath => Shortcut { cmd: true, shift: true, alt: true, ctrl: false, key: "c" },
            Command::SearchEditorRerun => cmd_shift("r"),
            Command::SearchEditorToggleContext => Shortcut { cmd: true, shift: false, alt: true, ctrl: false, key: "l" },
            Command::SearchEditorDeleteFileResults => Shortcut { cmd: true, shift: true, alt: false, ctrl: false, key: "backspace" },
            Command::RevealInFinder => Shortcut { cmd: true, shift: false, alt: true, ctrl: false, key: "r" },
            _ => return None,
        })
    }

    /// Two-stroke shortcuts like ⌘K ⌘T. Native menus can't show these.
    pub fn chord(self) -> Option<(Shortcut, Shortcut)> {
        Some(match self {
            Command::SelectTheme => (cmd("k"), cmd("t")),
            Command::OpenKeybindings => (cmd("k"), cmd("s")),
            Command::GitStageSelectedRanges => (cmd("k"), Shortcut { cmd: true, shift: false, alt: true, ctrl: false, key: "s" }),
            Command::GitUnstageSelectedRanges => (cmd("k"), cmd("n")),
            Command::GitRevertSelectedRanges => (cmd("k"), cmd("r")),
            Command::KeepEditor => (cmd("k"), plain("enter")),
            Command::FormatSelection => (cmd("k"), cmd("f")),
            Command::MoveToNextOccurrence => (cmd("k"), cmd("d")),
            Command::ToggleFold => (cmd("k"), cmd("l")),
            Command::FoldRecursively => (cmd("k"), cmd("[")),
            Command::UnfoldRecursively => (cmd("k"), cmd("]")),
            Command::FoldAll => (cmd("k"), cmd("0")),
            Command::UnfoldAll => (cmd("k"), cmd("j")),
            Command::CloseSavedEditors => (cmd("k"), plain("u")),
            Command::CloseGroupEditors => (cmd("k"), plain("w")),
            Command::CloseAllEditors => (cmd("k"), cmd("w")),
            Command::CompareWithSaved => (cmd("k"), plain("d")),
            Command::MarkdownPreviewSide => (cmd("k"), plain("v")),
            Command::ToggleZenMode => (cmd("k"), plain("z")),
            Command::ChangeLanguageMode => (cmd("k"), plain("m")),
            Command::TestingRunAll => (cmd(";"), plain("a")),
            Command::TestingRunAtCursor => (cmd(";"), plain("c")),
            Command::TestingDebugAtCursor => (cmd(";"), cmd("c")),
            Command::TestingRunCurrentFile => (cmd(";"), plain("f")),
            Command::TestingReRunLastRun => (cmd(";"), plain("l")),
            Command::TestingReRunFailed => (cmd(";"), plain("e")),
            Command::TestingCancel => (cmd(";"), cmd("x")),
            Command::TestingRefresh => (cmd(";"), cmd("r")),
            Command::TestingShowOutput => (cmd(";"), cmd("o")),
            _ => return None,
        })
    }

}

/// A command contributed by an extension, or registered by its program at run time.
#[derive(Clone, Debug)]
pub struct ExtCommand {
    pub id: &'static str,
    /// "Category: Title".
    pub title: &'static str,
    /// The extension's id.
    pub extension: String,
    /// Listed in the command palette (contributed in `package.json`).
    pub in_palette: bool,
    /// The extension is enabled.
    pub enabled: bool,
}

thread_local! {
    /// Never shrinks, so `Command::Ext` indices stay valid; a removed extension's commands are
    /// disabled instead.
    static EXT_COMMANDS: std::cell::RefCell<Vec<ExtCommand>> = const { std::cell::RefCell::new(Vec::new()) };
}

fn ext_command(i: u16) -> ExtCommand {
    EXT_COMMANDS.with(|e| e.borrow()[i as usize].clone())
}

fn ext_command_named(id: &str) -> Option<Command> {
    EXT_COMMANDS.with(|e| e.borrow().iter().position(|c| c.id == id && c.enabled).map(|i| Command::Ext(i as u16)))
}

/// Registers (or re-enables) an extension's command; a palette title replaces a missing one.
pub fn register_ext_command(id: &str, title: Option<&str>, extension: &str) -> Command {
    EXT_COMMANDS.with(|e| {
        let mut list = e.borrow_mut();
        let leak = |s: &str| -> &'static str { Box::leak(s.to_string().into_boxed_str()) };
        match list.iter().position(|c| c.id == id) {
            Some(i) => {
                let c = &mut list[i];
                c.enabled = true;
                c.extension = extension.to_string();
                if let Some(t) = title.filter(|t| *t != c.title) {
                    c.title = leak(t);
                    c.in_palette = true;
                }
                Command::Ext(i as u16)
            }
            None => {
                list.push(ExtCommand { id: leak(id), title: leak(title.unwrap_or(id)), extension: extension.to_string(), in_palette: title.is_some(), enabled: true });
                Command::Ext(list.len() as u16 - 1)
            }
        }
    })
}

/// Enables or disables every command of an extension.
pub fn set_ext_commands_enabled(extension: &str, enabled: bool) {
    EXT_COMMANDS.with(|e| e.borrow_mut().iter_mut().filter(|c| c.extension == extension).for_each(|c| c.enabled = enabled));
}

/// The extension a command belongs to.
pub fn ext_command_owner(command: Command) -> Option<String> {
    match command {
        Command::Ext(i) => Some(ext_command(i).extension),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extension_commands_are_found_by_id() {
        let c = register_ext_command("wordCount.show", Some("Word Count: Show"), "orbvane.word-count");
        assert_eq!(Command::from_id("wordCount.show"), Some(c));
        assert_eq!(c.title(), "Word Count: Show");
        assert!(Command::all().contains(&c));
        let hidden = register_ext_command("wordCount.internal", None, "orbvane.word-count");
        assert!(!Command::all().contains(&hidden));
        set_ext_commands_enabled("orbvane.word-count", false);
        assert_eq!(Command::from_id("wordCount.show"), None);
        assert!(!Command::all().contains(&c));
        assert_eq!(register_ext_command("wordCount.show", Some("Word Count: Show"), "orbvane.word-count"), c);
    }

    /// A key can only do one thing: no two commands share a default shortcut or chord, and no
    /// shortcut is the first stroke of a chord.
    #[test]
    fn shortcuts_are_unique() {
        let mut seen: Vec<(Shortcut, Command)> = Vec::new();
        for &c in Command::ALL {
            if let Some(s) = c.shortcut() {
                if let Some((_, other)) = seen.iter().find(|(x, _)| *x == s) {
                    panic!("{c:?} and {other:?} share {s:?}");
                }
                seen.push((s, c));
            }
        }
        let mut chords: Vec<((Shortcut, Shortcut), Command)> = Vec::new();
        for &c in Command::ALL {
            if let Some(ch) = c.chord() {
                if let Some((_, other)) = chords.iter().find(|(x, _)| *x == ch) {
                    panic!("{c:?} and {other:?} share a chord");
                }
                assert!(!seen.iter().any(|(s, _)| *s == ch.0), "{c:?}'s chord starts with another command's key");
                chords.push((ch, c));
            }
        }
    }
}
