#!/usr/bin/env python3
"""Writes THIRD-PARTY-NOTICES.md: the material in this repository that comes from others, and
the license texts of every crate compiled into the macOS app (from `cargo metadata` and the
crates' own license files in Cargo's registry).

Usage: python3 tools/third_party_notices.py   (from the repository root; run after changing
dependencies)
"""
import json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MIT = """Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."""

HEADER = f"""# Third-party notices

Orbvane is licensed under the MIT license or the Apache License 2.0, at your option
(`LICENSE-MIT`, `LICENSE-APACHE`). It includes, or is derived from, the material below, used
under the licenses shown. This file is generated by `tools/third_party_notices.py`.

## Material in this repository

### Color defaults, language service behaviour and wording

The color defaults in `crates/theme/src/registry.rs` (generated), parts of the HTML, CSS and JSON language services
in `crates/html`, `crates/css` and `crates/json` (the HTML scanner and parser structure, lint
rules and messages), and setting descriptions and command titles are derived from software
under the MIT license:

```
MIT License

Copyright (c) Microsoft Corporation.

{MIT}
```

### Browser data (`crates/css/data`, `crates/html/data`)

The CSS and HTML data files are derived from MIT-licensed software (Copyright (c) Microsoft
Corporation; the MIT license text above applies). Their descriptions come from
[MDN Web Docs](https://developer.mozilla.org) by Mozilla Contributors, licensed under
[CC-BY-SA 2.5](https://creativecommons.org/licenses/by-sa/2.5/); the descriptions as included
here are available under the same license. Their usage relevance values are built upon content
from Chrome Platform Status ([chromestatus.com](https://chromestatus.com)), licensed under
[CC-BY 2.5](https://creativecommons.org/licenses/by/2.5/).

### Emmet (`crates/app/src/emmet/`)

The abbreviation engine is a port of Emmet, and `crates/app/src/emmet/data/` holds its snippet
and lorem ipsum data:

```
MIT License

Copyright (c) 2020 Sergey Chikuyonok <serge.che@gmail.com>

{MIT}
```

## Rust crates

The macOS app is built from these crates. Each one's license texts follow, grouped where they
are identical.
"""

LICENSE_FILE = re.compile(r"^(licen[cs]e|copying|notice|unlicense)([-._].*)?$", re.I)


def run(*args):
    return subprocess.run(args, cwd=ROOT, check=True, capture_output=True, text=True).stdout


def main():
    used = set()
    for target in ("aarch64-apple-darwin", "x86_64-apple-darwin"):
        out = run("cargo", "tree", "--workspace", "--target", target, "-e", "normal", "--prefix", "none", "--format", "{p}")
        for line in out.splitlines():
            m = re.match(r"(\S+) v(\S+)", line)
            if m:
                used.add((m.group(1), m.group(2)))
    meta = json.loads(run("cargo", "metadata", "--format-version", "1"))
    workspace = set(meta["workspace_members"])
    crates = []
    for p in meta["packages"]:
        if p["id"] in workspace or (p["name"], p["version"]) not in used:
            continue
        crates.append(p)
    crates.sort(key=lambda p: (p["name"], p["version"]))

    groups = {}  # text -> [crate labels]
    rows = []
    for p in crates:
        label = f"{p['name']} {p['version']}"
        lic = p.get("license") or "see license file"
        rows.append(f"| {p['name']} | {p['version']} | {lic} | {p.get('repository') or ''} |")
        folder = os.path.dirname(p["manifest_path"])
        files = sorted(f for f in os.listdir(folder) if LICENSE_FILE.match(f) and os.path.isfile(os.path.join(folder, f)))
        texts = []
        for f in files:
            with open(os.path.join(folder, f), encoding="utf-8", errors="replace") as fh:
                texts.append(fh.read().strip())
        if not texts:
            # No license file in the package: the license named in its manifest, with its authors.
            authors = ", ".join(p.get("authors") or []) or f"the {p['name']} authors"
            if "MIT" in lic:
                texts.append(f"MIT License\n\nCopyright (c) {authors}\n\n{MIT}")
            if "Apache-2.0" in lic:
                texts.append("Apache License 2.0: the full text is in LICENSE-APACHE.")
            if not texts:
                texts.append(f"Licensed under {lic}.")
        for t in texts:
            groups.setdefault(t, []).append(label)

    out = [HEADER, "| Crate | Version | License | Repository |", "|---|---|---|---|", *rows, "", "## License texts", ""]
    for text, labels in sorted(groups.items(), key=lambda kv: kv[1][0]):
        out.append("Used by: " + ", ".join(sorted(set(labels))))
        out.append("")
        out.append("```")
        out.append(text.replace("```", "'''"))
        out.append("```")
        out.append("")
    with open(os.path.join(ROOT, "THIRD-PARTY-NOTICES.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"THIRD-PARTY-NOTICES.md: {len(crates)} crates, {len(groups)} license texts")


if __name__ == "__main__":
    sys.exit(main())
